export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  ACHIEVEMENTS: '/achievements',
  CONTACTS: '/contacts',
  DIRECTIONS: '/directions',
  DIRECTIONSDETAIL: '/directionsdetail',
  DOCUMENTS: '/documents',
  DIRECTOR: '/director',
  DEPUTY: '/deputy',
  INFRASTRUCTURE: '/infrastructure',
  STUDYPLAN: '/studyplan',
  STUDYDETAIL: '/studydetail',
  SCHEDULE: '/schedule',
  FAQ: '/faq',
  MANAGEMENT: '/management',
  GALLERY: '/gallery',
  CONDITIONS: '/conditions',
  NEWSSECTION: '/newsSection',
  NEWSLIST: '/newsList',
  NEWSDETAIL: '/newsDetail',
  LOGIN: '/login',
  ADMINNEWS: '/adminNews',
  ACADEMIC: '/academic'
};